### PR TITLE
feat: make service gateway response configurable

### PR DESCRIPTION
**Pull request by nicoloboschi**
* Now when the agent fails by default sets a new header "langstream-error-type" which has two possible values: INTERNAL_ERROR or INVALID_RECORD. The default is INTERNAL_ERROR. 
* When the service gateway gets the message it looks for this header and decide the status code (INVALID_RECORD -> 400, INTERNAL_ERROR -> 500). **This is a breaking change** since before that it was always returning 200. It also looks the following header until one it's not blank: langstream-error-message, langstream-error-cause-message, langstream-error-root-cause-message.
* These new headers are sent to the deadletter along with the existing headers: error-msg, cause-msg, root-cause-msg (note that those headers are still present to not break compatibility but they're not checked by the gateway)
* From the agent perspective, to set an error as INVALID_RECORD it can be done in this way:
  1. In Java agents, you can emit the result with appropriate type
  2. In Python you can raise an Exception in the sink or processor 
  ```
  def process(self, record):
        logging.info("Processing record" + str(record))
        from langstream import InvalidRecordError
        raise InvalidRecordError("record was not ok:" + str(record))
  ```
  Any other exception will treat the error as INTERNAL_ERROR

### CODE REVIEW

**Comment by cdbartholomew** [comment]
For the Python agent case, does it send the message the DLQ when you raise the InvalidRecordException?

**Comment by cdbartholomew** [comment]
Another pattern we have started to use is to short circuit the request if it has invalid parameters and send an error response back to the gateway right away. See here: https://github.com/vectorize-io/langstream-deploy/blob/develop/applications/prod-pipelines/python/templates/embedders/python/validate_retrieve.py

**Comment by nicoloboschi** [comment]
> For the Python agent case, does it send the message the DLQ when you raise the InvalidRecordException?

The DLQ is managed by the topic source so most of the use cases are covered. (e.g. python processor with topic input)
For Python sources, DLQ it's not implemented at all. If your pipeline starts from a python source, it will never sent to a DLQ by langstream.
`InvalidRecordException` is meant only to mark the error to 400. To mark it as 500, raise instead a  generic exception

**Comment by nicoloboschi** [comment]
> Another pattern we have started to use is to short circuit the request if it has invalid parameters and send an error response back to the gateway right away. See here: https://github.com/vectorize-io/langstream-deploy/blob/develop/applications/prod-pipelines/python/templates/embedders/python/validate_retrieve.py

It's totally fine to by-pass the DLQ. 
In order to set the error type and message, you need to set the following headers in the output topic message:
```
langstream-error-type: INVALID_RECORD
langstream-error-message: "Validation error: invalid metadata filters provided"
```
They will be read by the API gateway and used in the HTTP response.


If you use DQL they are automatically populated but you can override them with a `compute` step or anything else.

**Pull request merged**
